### ISSUE TITLE
前もってポータルでワークスペースを作成しなければならないのでしょうか

### ISSUE THREAD

**Issue by yoichinak** [seosoft/PredMaint-JP#5]
> 下のセルを実行する前に、Azure ポータルで **Azure Machine Learning ワークスペース** を作成してください。

issue #1
commit  b24b3d1bb07340a09ab3f1cc87d84c403bffe1eb

この訳注の作業は本当に必要なのでしょうか。`Workspace.create()` のセルの実行だけで済まないのでしょうか。リソースを削除してやり直してみた感じでは、前もってポータルでワークスペースを作っておかなくても、最後まで実行できたと思います。

**Comment by seosoft** [comment]
指摘ありがとうございます。
編集時に他のコンテンツと混同して入れてしまったものだと思います。（すみません、定かではなく・・・）
